"""peridiek_medewerker

Revision ID: 090cea3a7793
Revises: 5f1c2316cd65
Create Date: 2019-03-12 16:22:30.748518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090cea3a7793'
down_revision = '5f1c2316cd65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_trello_cards', sa.Column('trello_periodiek_medewerker_id', sa.String(length=256), nullable=True))
    op.add_column('project_trello_cards', sa.Column('trello_periodiek_medewerker_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_trello_cards', 'trello_periodiek_medewerker_name')
    op.drop_column('project_trello_cards', 'trello_periodiek_medewerker_id')
    # ### end Alembic commands ###
