"""init

Revision ID: 5f1c2316cd65
Revises: 
Create Date: 2019-03-01 19:35:00.203897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1c2316cd65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('lock', sa.Integer(), nullable=False),
    sa.Column('trello_key', sa.String(length=512), nullable=True),
    sa.Column('trello_token', sa.String(length=512), nullable=True),
    sa.Column('simplicate_key', sa.String(length=512), nullable=True),
    sa.Column('simplicate_secret', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('lock')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('trello_id', sa.String(length=512), nullable=False),
    sa.Column('simplicate_id', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('simplicate_id'),
    sa.UniqueConstraint('trello_id')
    )
    op.create_table('jaarwerk',
    sa.Column('lock', sa.Integer(), nullable=False),
    sa.Column('source_board_name', sa.String(length=256), nullable=True),
    sa.Column('source_board_id', sa.String(length=256), nullable=True),
    sa.Column('target_board_name', sa.String(length=256), nullable=True),
    sa.Column('target_board_id', sa.String(length=256), nullable=True),
    sa.Column('target_list_name', sa.String(length=256), nullable=True),
    sa.Column('target_list_id', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('lock')
    )
    op.create_table('jaarwerk_result',
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('archive_id')
    )
    op.create_table('klaar_archief_links',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('source_id', sa.String(length=256), nullable=True),
    sa.Column('source_name', sa.String(length=256), nullable=True),
    sa.Column('target_id', sa.String(length=256), nullable=True),
    sa.Column('target_name', sa.String(length=256), nullable=True),
    sa.Column('board_id', sa.String(length=256), nullable=True),
    sa.Column('board_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('source_id', 'target_id', name='_source_target_uc')
    )
    op.create_table('klaar_archief_result',
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('archive_id')
    )
    op.create_table('maandwerk',
    sa.Column('lock', sa.Integer(), nullable=False),
    sa.Column('source_board_name', sa.String(length=256), nullable=True),
    sa.Column('source_board_id', sa.String(length=256), nullable=True),
    sa.Column('source_list_month_name', sa.String(length=256), nullable=True),
    sa.Column('source_list_month_id', sa.String(length=256), nullable=True),
    sa.Column('source_list_quarter_name', sa.String(length=256), nullable=True),
    sa.Column('source_list_quarter_id', sa.String(length=256), nullable=True),
    sa.Column('target_board_name', sa.String(length=256), nullable=True),
    sa.Column('target_board_id', sa.String(length=256), nullable=True),
    sa.Column('source_list_name', sa.String(length=256), nullable=True),
    sa.Column('source_list_id', sa.String(length=256), nullable=True),
    sa.Column('target_list_name', sa.String(length=256), nullable=True),
    sa.Column('target_list_id', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('lock')
    )
    op.create_table('maandwerk_copy_result',
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('archive_id')
    )
    op.create_table('maandwerk_move_result',
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('archive_id')
    )
    op.create_table('project_trello_cards',
    sa.Column('lock', sa.Integer(), nullable=False),
    sa.Column('planning_periodiek_werk_board_name', sa.String(length=256), nullable=True),
    sa.Column('planning_periodiek_werk_board_id', sa.String(length=256), nullable=True),
    sa.Column('planning_jaarwerk_board_name', sa.String(length=256), nullable=True),
    sa.Column('planning_jaarwerk_board_id', sa.String(length=256), nullable=True),
    sa.Column('nog_te_plannen_board_name', sa.String(length=256), nullable=True),
    sa.Column('nog_te_plannen_board_id', sa.String(length=256), nullable=True),
    sa.Column('month_list_name', sa.String(length=256), nullable=True),
    sa.Column('month_list_id', sa.String(length=256), nullable=True),
    sa.Column('quarter_list_name', sa.String(length=256), nullable=True),
    sa.Column('quarter_list_id', sa.String(length=256), nullable=True),
    sa.Column('year_list_name', sa.String(length=256), nullable=True),
    sa.Column('year_list_id', sa.String(length=256), nullable=True),
    sa.Column('afspraken_planning_volgend_jaar_list_name', sa.String(length=256), nullable=True),
    sa.Column('afspraken_planning_volgend_jaar_list_id', sa.String(length=256), nullable=True),
    sa.Column('exception_list_name', sa.String(length=256), nullable=True),
    sa.Column('exception_list_id', sa.String(length=256), nullable=True),
    sa.Column('periodiek_sjablonen_list_name', sa.String(length=256), nullable=True),
    sa.Column('periodiek_sjablonen_list_id', sa.String(length=256), nullable=True),
    sa.Column('jaarwerk_sjablonen_list_name', sa.String(length=256), nullable=True),
    sa.Column('jaarwerk_sjablonen_list_id', sa.String(length=256), nullable=True),
    sa.Column('periodiek_sjablonen_card_name', sa.String(length=256), nullable=True),
    sa.Column('periodiek_sjablonen_card_id', sa.String(length=256), nullable=True),
    sa.Column('jaarwerk_sjablonen_card_name', sa.String(length=256), nullable=True),
    sa.Column('jaarwerk_sjablonen_card_id', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('lock')
    )
    op.create_table('project_trello_results',
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('archive_id')
    )
    op.create_table('simplicate_trello_codes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('simplicate_code', sa.String(length=12), nullable=True),
    sa.Column('simplicate_id', sa.String(length=256), nullable=True),
    sa.Column('monthly', sa.Boolean(), nullable=False),
    sa.Column('quarterly', sa.Boolean(), nullable=False),
    sa.Column('yearly', sa.Boolean(), nullable=False),
    sa.Column('jaarwerk', sa.Boolean(), nullable=False),
    sa.Column('trello_code', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('access', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project_trello_results_card',
    sa.Column('result_card_id', sa.Integer(), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.String(length=256), nullable=True),
    sa.Column('board_name', sa.String(length=256), nullable=True),
    sa.Column('list_id', sa.String(length=256), nullable=True),
    sa.Column('list_name', sa.String(length=256), nullable=True),
    sa.Column('card_id', sa.String(length=256), nullable=True),
    sa.Column('card_name', sa.String(length=256), nullable=True),
    sa.Column('card_desc', sa.String(length=1024), nullable=True),
    sa.Column('card_link', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['archive_id'], ['project_trello_results.archive_id'], ),
    sa.PrimaryKeyConstraint('result_card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_trello_results_card')
    op.drop_table('users')
    op.drop_table('simplicate_trello_codes')
    op.drop_table('project_trello_results')
    op.drop_table('project_trello_cards')
    op.drop_table('maandwerk_move_result')
    op.drop_table('maandwerk_copy_result')
    op.drop_table('maandwerk')
    op.drop_table('klaar_archief_result')
    op.drop_table('klaar_archief_links')
    op.drop_table('jaarwerk_result')
    op.drop_table('jaarwerk')
    op.drop_table('employees')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
